"""
Minimal back-tester for Hull-Suite signal series.

Pairs an OHLCV frame with a {-1, 0, +1} signal series (typically the output
of :func:`qufin.strategies.hull_strategy.generate_signals`) and computes the
standard performance statistics.

The convention here matches the rest of the package: ``signal[t]`` is the
position **held from bar t into bar t+1**, so bar-t's signal earns bar-t+1's
log-return.  No look-ahead is introduced.

Usage
-----
    >>> from qufin.strategies.hull_strategy import generate_signals
    >>> from qufin.strategies.hull_backtest import backtest_hull
    >>> sig = generate_signals(bars, fast_length=50, slow_length=60)
    >>> report = backtest_hull(bars, sig)
    >>> print(report.summary())
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import polars as pl

from ..indicators._types import to_numpy_1d

# Annualisation factor for daily bars (252 trading days/year).
_ANNUAL_DAILY = float(np.sqrt(252))


@dataclass(slots=True, frozen=True)
class HullBacktestResult:
    """
    Output of :func:`backtest_hull`.

    Attributes
    ----------
    log_returns : np.ndarray
        Strategy log-returns per bar, aligned to the OHLCV frame.  The first
        entry is 0 by construction (no prior signal).
    equity : np.ndarray
        Cumulative log-equity curve, ``exp(cumsum(log_returns))``.
    total_return : float
        Net return over the period: ``equity[-1] − 1``.
    annual_return : float
        Annualised log-return × ``annualizer`` (defaults to √252-scaled mean
        × 252).
    sharpe : float
        Annualised Sharpe ratio of strategy log-returns.
    max_drawdown : float
        Maximum peak-to-trough drawdown of the equity curve (negative number).
    win_rate : float
        Fraction of *closed trades* whose realised log-return is > 0.  A
        "trade" is a continuous run of non-zero signal of constant sign.
    n_trades : int
        Number of closed trades.
    avg_trade : float
        Mean log-return per closed trade.
    """

    log_returns: np.ndarray
    equity: np.ndarray
    total_return: float
    annual_return: float
    sharpe: float
    max_drawdown: float
    win_rate: float
    n_trades: int
    avg_trade: float

    def summary(self) -> str:
        return "\n".join(
            [
                "Hull-Suite Backtest",
                "=" * 35,
                f"  Total return  : {self.total_return * 100:.2f}%",
                f"  Annual return : {self.annual_return * 100:.2f}%",
                f"  Sharpe (ann.) : {self.sharpe:.4f}",
                f"  Max drawdown  : {self.max_drawdown * 100:.2f}%",
                f"  Trades        : {self.n_trades}",
                f"  Win rate      : {self.win_rate * 100:.1f}%",
                f"  Avg trade     : {self.avg_trade * 100:.3f}%",
            ]
        )


def _extract_close(ohlcv: pl.DataFrame | np.ndarray | pl.Series) -> np.ndarray:
    match ohlcv:
        case pl.DataFrame():
            if "close" not in ohlcv.columns:
                raise ValueError("OHLCV DataFrame must contain a 'close' column")
            return to_numpy_1d(ohlcv["close"])
        case pl.Series() | np.ndarray():
            return to_numpy_1d(ohlcv)
        case _:
            return to_numpy_1d(np.asarray(ohlcv))


def _trade_returns(signals: np.ndarray, bar_log_ret: np.ndarray) -> np.ndarray:
    """
    Sum the bar log-returns within each constant-sign signal run.

    A trade starts when ``signals[t-1] == 0`` and ``signals[t] != 0`` (or on
    a flip from +1↔−1) and closes when the signal returns to 0 (or flips).
    The realised log-return of the trade is the cumulative strategy
    log-return over those bars.
    """
    n = signals.shape[0]
    trade_pnls: list[float] = []
    in_trade = False
    cur_sign = 0
    cur_pnl = 0.0
    for t in range(n):
        s = int(signals[t])
        # The bar return earned at index t was generated by signals[t-1].
        if in_trade and t > 0:
            cur_pnl += bar_log_ret[t]
        # Detect close (signal returns to 0 or flips sign).
        if in_trade and s != cur_sign:
            trade_pnls.append(cur_pnl)
            in_trade = False
            cur_pnl = 0.0
            cur_sign = 0
        # Detect open (flat → directional).
        if not in_trade and s != 0:
            in_trade = True
            cur_sign = s
            cur_pnl = 0.0
    if in_trade:
        trade_pnls.append(cur_pnl)
    return np.asarray(trade_pnls, dtype=np.float64)


def backtest_hull(
    ohlcv_df: pl.DataFrame | np.ndarray | pl.Series,
    signals: pl.Series | np.ndarray,
    annualizer: float = _ANNUAL_DAILY,
) -> HullBacktestResult:
    """
    Run a vector backtest on a signal series.

    Parameters
    ----------
    ohlcv_df : polars.DataFrame, polars.Series, or 1-D array
        OHLCV frame (column ``'close'`` is used) or a bare close series.
    signals : polars.Series or 1-D array
        Position series produced by
        :func:`qufin.strategies.hull_strategy.generate_signals` — values in
        ``{-1, 0, +1}``.  Must be the same length as ``ohlcv_df``.
    annualizer : float, default √252
        Factor used to annualise the Sharpe ratio.  Use ``√(252·N)`` for
        intraday bars where ``N`` is bars-per-day.

    Returns
    -------
    HullBacktestResult
        Per-bar strategy log-returns and equity curve plus headline stats
        (total return, annualised return, Sharpe, max drawdown, win rate).
    """
    close = _extract_close(ohlcv_df)
    sig = to_numpy_1d(signals).astype(np.int8)
    if close.shape[0] != sig.shape[0]:
        raise ValueError(
            f"close and signals must share length ({close.shape[0]} vs {sig.shape[0]})"
        )
    if close.shape[0] < 2:
        raise ValueError("need at least 2 bars to compute returns")

    bar_log_ret = np.zeros_like(close)
    bar_log_ret[1:] = np.diff(np.log(np.maximum(close, 1e-12)))

    # signals[t-1] is the position held from t-1 → t, earning bar_log_ret[t].
    strat_ret = np.zeros_like(close)
    strat_ret[1:] = sig[:-1].astype(np.float64) * bar_log_ret[1:]

    cum_log = np.cumsum(strat_ret)
    equity = np.exp(cum_log)
    total_return = float(equity[-1] - 1.0)
    mean = float(np.mean(strat_ret))
    std = float(np.std(strat_ret))
    sharpe = float(mean / std * annualizer) if std > 1e-12 else 0.0
    annual_return = float(mean * (annualizer**2))

    peak = np.maximum.accumulate(equity)
    drawdown = equity / peak - 1.0
    max_dd = float(np.min(drawdown))

    trade_pnls = _trade_returns(sig, bar_log_ret)
    n_trades = int(trade_pnls.shape[0])
    win_rate = float(np.mean(trade_pnls > 0.0)) if n_trades > 0 else 0.0
    avg_trade = float(np.mean(trade_pnls)) if n_trades > 0 else 0.0

    return HullBacktestResult(
        log_returns=strat_ret,
        equity=equity,
        total_return=total_return,
        annual_return=annual_return,
        sharpe=sharpe,
        max_drawdown=max_dd,
        win_rate=win_rate,
        n_trades=n_trades,
        avg_trade=avg_trade,
    )
